version: 1
updated: '2026-01-10'
policy: No PDFs stored in repo. Keep canonical URLs + metadata here. Store your summaries
  in docs/reference/extracts/ keyed by source_id.
sources:
- source_id: SRC-0001
  title: Open Dog Academy chat/project planning artifacts (this conversation)
  authors: ''
  publisher: ''
  year: ''
  url: ''
  notes: ''
- source_id: SRC-0002
  title: S1_ Housing Access (Deep Research Output)
  authors: ''
  publisher: ''
  year: ''
  url: ''
  notes: ''
- source_id: SRC-0003
  title: Open Dog Academy – Multi-Tier Curriculum Research (Deep Research Output)
  authors: ''
  publisher: ''
  year: ''
  url: ''
  notes: ''
- source_id: SRC-0004
  title: Service Animals | ADA.gov
  authors: ''
  publisher: ''
  year: ''
  url: https://www.ada.gov/topics/service-animals/
  notes: ''
- source_id: SRC-0005
  title: 'ADA Requirements: Service Animals | ADA.gov'
  authors: ''
  publisher: ''
  year: ''
  url: https://www.ada.gov/resources/service-animals-2010-requirements/
  notes: ''
- source_id: SRC-0006
  title: Assistance Animals | HUD.gov
  authors: ''
  publisher: ''
  year: ''
  url: https://www.hud.gov/helping-americans/assistance-animals
  notes: ''
- source_id: SRC-0007
  title: HUD Assistance Animals Fact Sheet (FHEO-2020-01) PDF
  authors: ''
  publisher: ''
  year: ''
  url: https://www.hud.gov/sites/dfiles/PA/documents/AsstAnimalsGuidFS1-24-20.pdf
  notes: ''
- source_id: SRC-0008
  title: HUD/DOJ Joint Statement on Reasonable Accommodations (FHA)
  authors: ''
  publisher: ''
  year: ''
  url: https://www.hud.gov/sites/documents/huddojstatement.pdf
  notes: ''
- source_id: SRC-0009
  title: Taking a Service Animal to Work | ADA National Network
  authors: ''
  publisher: ''
  year: ''
  url: https://adata.org/service-animal-resource-hub-work
  notes: ''
- source_id: SRC-0010
  title: Taking a Service Animal to School | ADA National Network
  authors: ''
  publisher: ''
  year: ''
  url: https://adata.org/service-animal-resource-hub-school
  notes: ''
- source_id: SRC-0011
  title: Service Animals | askJAN.org (Job Accommodation Network)
  authors: ''
  publisher: ''
  year: ''
  url: https://askjan.org/topics/servanim.cfm
  notes: ''
- source_id: SRC-0012
  title: WCAG Overview | W3C WAI
  authors: ''
  publisher: ''
  year: ''
  url: https://www.w3.org/WAI/standards-guidelines/wcag/
  notes: ''
- source_id: SRC-0013
  title: Managing reactive behavior | Cornell University CVM
  authors: ''
  publisher: ''
  year: ''
  url: https://www.vet.cornell.edu/departments-centers-and-institutes/riney-canine-health-center/canine-health-information/managing-reactive-behavior
  notes: ''
- source_id: SRC-0014
  title: First Aid for Dogs | VCA Animal Hospitals
  authors: ''
  publisher: ''
  year: ''
  url: https://vcahospitals.com/know-your-pet/first-aid-for-dogs
  notes: ''
- source_id: SRC-0015
  title: Calorie Calculator | Pet Nutrition Alliance
  authors: ''
  publisher: ''
  year: ''
  url: https://petnutritionalliance.org/resources/calorie-calculator/
  notes: ''
- source_id: SRC-0016
  title: Heatstroke in Dogs | PetMD
  authors: ''
  publisher: ''
  year: ''
  url: https://www.petmd.com/dog/conditions/systemic/heatstroke-dogs
  notes: ''
- source_id: SRC-0017
  title: Hypothermia in Dogs | VEG ER
  authors: ''
  publisher: ''
  year: ''
  url: https://www.veg.com/post/10-tips-for-protecting-your-dog-from-hypothermia-this-winter
  notes: ''
- source_id: SRC-0018
  title: CAPC Lyme Disease Guidelines
  authors: ''
  publisher: ''
  year: ''
  url: https://capcvet.org/guidelines/lyme-disease/
  notes: ''
- source_id: SRC-0019
  title: Canine PFDs | BoatUS Foundation
  authors: ''
  publisher: ''
  year: ''
  url: https://boatus.org/findings/33
  notes: ''
- source_id: SRC-0020
  title: 'Vibration Collars: What You Should Know | Whole Dog Journal'
  authors: ''
  publisher: ''
  year: ''
  url: https://www.whole-dog-journal.com/training/good-vibrations/
  notes: ''
- source_id: SRC-0021
  title: Why E-Collar Dog Training Is Not Recommended | Whole Dog Journal
  authors: ''
  publisher: ''
  year: ''
  url: https://www.whole-dog-journal.com/training/why-e-collar-dog-training-is-not-recommended/
  notes: ''
- source_id: SRC-0022
  title: A revised taxonomy of assistance animals (paper)
  authors: ''
  publisher: ''
  year: ''
  url: https://pmc.ncbi.nlm.nih.gov/articles/PMC4540185/
  notes: ''
- source_id: SRC-0023
  title: 'Service Dogs: Ethics and Education | IAABC Foundation Journal'
  authors: ''
  publisher: ''
  year: ''
  url: https://journal.iaabcfoundation.org/service-dogs-ethics-and-education/
  notes: ''
- source_id: SRC-0024
  title: ADI Summary of Standards (2025) PDF
  authors: ''
  publisher: ''
  year: ''
  url: https://assistancedogsinternational.org/clientuploads/Summary%20of%20Standards/2025_ADI_Summary_of_Standards.pdf
  notes: ''
- source_id: SRC-0025
  title: Service Dog Tasks | WVU Hearts of Gold
  authors: ''
  publisher: ''
  year: ''
  url: https://heartsofgold.wvu.edu/service-dogs/training-methods/service-dog-tasks
  notes: ''
- source_id: SRC-0026
  title: Picking a Service Dog Puppy Prospect | Psych Dog Partners
  authors: ''
  publisher: ''
  year: ''
  url: https://www.psychdogpartners.org/resources/getting-a-dog/pick-puppy-service-dog-prospect
  notes: ''
- source_id: SRC-0027
  title: Breed, age and puppyhood socialisation linked to canine personality | University
    of Helsinki
  authors: ''
  publisher: ''
  year: ''
  url: https://www.helsinki.fi/en/news/dogs/breed-age-and-puppyhood-socialisation-linked-canine-personality
  notes: ''
- source_id: SRC-0028
  title: The Puppies’ Age at Adoption Time Influences the Behavioral Responses of
    Adult Dog (paper)
  authors: ''
  publisher: ''
  year: ''
  url: https://pmc.ncbi.nlm.nih.gov/articles/PMC11860672/
  notes: ''
- source_id: SRC-0029
  title: Dog Behavior Assessments in Veterinary Care | Weave
  authors: ''
  publisher: ''
  year: ''
  url: https://www.getweave.com/dog-behavior-assessment/
  notes: ''
- source_id: SRC-0030
  title: 'Service Dogs in Schools: What You Need to Know | PublicSchoolWORKS'
  authors: ''
  publisher: ''
  year: ''
  url: https://corp.publicschoolworks.com/resource/service-dogs-in-schools-what-you-need-to-know/
  notes: ''
- source_id: SRC-0031
  title: Fair Housing and Assistance Animals Fact Sheet | DLCV
  authors: ''
  publisher: ''
  year: ''
  url: https://www.dlcv.org/wp-content/uploads/2021/01/Fair-Housing-and-Assistance-Animals-Fact-Sheet.pdf
  notes: ''
- source_id: SRC-0032
  title: Bazelon Center ESA Fact Sheet (2017)
  authors: ''
  publisher: ''
  year: ''
  url: https://www.bazelon.org/wp-content/uploads/2017/04/2017-06-16-Emotional-Support-Animal-Fact-Sheet-for-Website-final.pdf
  notes: ''
- source_id: SRC-0033
  title: EEOC denial of service animal accommodation insight (Venable LLP)
  authors: ''
  publisher: ''
  year: ''
  url: https://www.venable.com/insights/publications/2025/07/eeoc-sues-employer-over-denial-of-service
  notes: ''
- source_id: SRC-0034
  title: Behavior Problems and Service Dog Candidates | Cooperative Paws
  authors: ''
  publisher: ''
  year: ''
  url: https://cooperativepaws.com/service-dog-behavior-problem/
  notes: ''
- source_id: SRC-0035
  title: What are Psychiatric Service Dogs Tasks? | Medical Mutts
  authors: ''
  publisher: ''
  year: ''
  url: https://www.medicalmutts.org/post/what-are-psychiatric-service-dogs-tasks
  notes: ''
- source_id: SRC-0036
  title: Wave 0 Tasks and Search Plan (Deep Research Output)
  authors: ''
  publisher: ''
  year: ''
  url: ''
  notes: ''
- source_id: SRC-0037
  title: Open Dog Academy_ Public Access (ADA) Standards and Training (Deep Research
    Output)
  authors: ''
  publisher: ''
  year: ''
  url: ''
  notes: ''
- source_id: SRC-0038
  title: Research Roadmap Clarification (Deep Research Output)
  authors: ''
  publisher: ''
  year: ''
  url: ''
  notes: ''
- source_id: SRC-0039
  title: Research Roadmap Clarification-1 (Deep Research Output)
  authors: ''
  publisher: ''
  year: ''
  url: ''
  notes: ''
- source_id: SRC-0040
  title: Research Roadmap Clarification-2 (Deep Research Output)
  authors: ''
  publisher: ''
  year: ''
  url: ''
  notes: ''
- source_id: SRC-0041
  title: Frequently Asked Questions about Service Animals and the ADA | ADA.gov
  authors: ''
  publisher: ''
  year: ''
  url: https://www.ada.gov/resources/service-animals-faqs/
  notes: ''
- source_id: SRC-0042
  title: 'eCFR :: 28 CFR 35.104 — Definitions (Service animal)'
  authors: ''
  publisher: ''
  year: ''
  url: https://www.ecfr.gov/current/title-28/chapter-I/part-35/subpart-A/section-35.104
  notes: ''
- source_id: SRC-0043
  title: 'eCFR :: 28 CFR 36.104 — Definitions (Service animal)'
  authors: ''
  publisher: ''
  year: ''
  url: https://www.ecfr.gov/current/title-28/chapter-I/part-36/subpart-A/section-36.104
  notes: ''
- source_id: SRC-0044
  title: 28 CFR 35.136 — Service animals (Cornell LII mirror)
  authors: ''
  publisher: ''
  year: ''
  url: https://www.law.cornell.edu/cfr/text/28/35.136
  notes: ''
- source_id: SRC-0045
  title: IAADP Minimum Training Standards for Public Access
  authors: ''
  publisher: ''
  year: ''
  url: https://iaadp.org/membership/iaadp-minimum-training-standards-for-public-access/
  notes: ''
- source_id: SRC-0046
  title: Can I charge maintenance or cleaning fees for customers who bring service
    animals? | ADATA
  authors: ''
  publisher: ''
  year: ''
  url: https://adata.org/faq/can-i-charge-maintenance-or-cleaning-fees-customers-who-bring-service-animals-my-business
  notes: ''
- source_id: SRC-0047
  title: Service Animal Resource Hub — Basics | ADATA
  authors: ''
  publisher: ''
  year: ''
  url: https://adata.org/service-animal-resource-hub-basics
  notes: ''
- source_id: SRC-0048
  title: AskJAN Consultants’ Corner (Service Animals / Workplace)
  authors: ''
  publisher: ''
  year: ''
  url: https://askjan.org/publications/consultants-corner/vol12iss04.cfm
  notes: ''
- source_id: SRC-0049
  title: HUD Notice FHEO-2020-01 (archived PDF)
  authors: ''
  publisher: ''
  year: ''
  url: https://www.dlcv.org/wp-content/uploads/2021/01/FHEO-2020-01.pdf
  notes: ''
- source_id: SRC-0050
  title: Notice of Withdrawal of Guidance Documents (Sept 2025)
  authors: ''
  publisher: ''
  year: ''
  url: https://leadingage.org/wp-content/uploads/2025/09/Notice-of-Withdrawal-of-Guidance-Documents-FINAL-09.17.2025.pdf
  notes: ''
